spring:
  application:
    name: app
  
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariPool-TicketIS
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      leak-detection-threshold: 60000
      auto-commit: false
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        cache:
          use_second_level_cache: true
          region:
            factory_class: infinispan
  
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  
  servlet:
    multipart:
      enabled: true
      max-file-size: 3000MB
      max-request-size: 3000MB
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.web.servlet.MultipartAutoConfiguration

logging:
  level:
    org.apache.activemq.audit: WARN
    org.apache.activemq.audit.message: OFF
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    com.ticketis.app.aspect.CacheStatisticsAspect: INFO

loggers: org.eclipse.jetty,org.jboss.logging,org.apache.activemq.artemis.core.server,org.apache.activemq.artemis.utils,org.apache.activemq.artemis.journal,org.apache.activemq.artemis.jms.server,org.apache.activemq.artemis.integration.bootstrap,org.apache.activemq.audit.base,org.apache.activemq.audit.message,org.apache.activemq.audit.resource

app:
  import:
    upload-dir: uploads/import
    distributed-threshold: 8000
  cache:
    statistics:
      enabled: true

db:
  init:
    script:
      path: db/init/01-create-schema.sql

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket-name: ${MINIO_BUCKET_NAME:myapp-bucket}
  presigned-url-expiry: 3600